# Generated by Django 5.1.15 on 2026-08-13 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmembership',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.avatar'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='channels', through='academy.ChannelMembership', to='avatar.avatar'),
        ),
        migrations.AddField(
            model_name='channel',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='academy.guild'),
        ),
        migrations.AddField(
            model_name='guildmembership',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_memberships', to='avatar.avatar'),
        ),
        migrations.AddField(
            model_name='guildmembership',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academy.guild'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='avatar.avatar'),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='academy.channel'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('avatar', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='guildmembership',
            unique_together={('avatar', 'guild')},
        ),
    ]
