# Generated by Django 5.1.15 on 2026-08-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='angle_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constellation',
            name='is_north_star',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constellation',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='orbit_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
