# Generated by Django 5.1.15 on 2026-08-13 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmap', '0002_constellation_angle_deg_constellation_is_north_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='planets',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ConstellationEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='starmap.constellation')),
                ('from_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='starmap.milestone')),
                ('to_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='starmap.milestone')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('constellation', 'from_milestone', 'to_milestone'), name='unique_edge_per_constellation'), models.CheckConstraint(condition=models.Q(('from_milestone', models.F('to_milestone')), _negated=True), name='no_self_edge')],
            },
        ),
    ]
