# Generated by Django 5.1.15 on 2026-08-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmap', '0003_milestone_planets_constellationedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
