# Generated by Django 5.1.15 on 2026-08-13 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sun_sign', models.CharField(blank=True, max_length=30)),
                ('moon_sign', models.CharField(blank=True, max_length=30)),
                ('rising_sign', models.CharField(blank=True, max_length=30)),
                ('jung_archetype', models.CharField(blank=True, max_length=50)),
                ('mbti', models.CharField(blank=True, max_length=10)),
                ('visionary_trait', models.TextField(blank=True)),
                ('divergent_trait', models.TextField(blank=True)),
                ('recommended_heroic_path', models.CharField(blank=True, choices=[('earthwatcher', 'Earthwatcher'), ('peacebringer', 'Peacebringer'), ('storyteller', 'Storyteller'), ('innovator', 'Innovator'), ('dreamwalker', 'Dreamwalker'), ('truthseeker', 'Truthseeker')], max_length=20)),
                ('recommended_learning_path', models.CharField(blank=True, choices=[('scholar', 'Scholar'), ('wayfinder', 'Wayfinder'), ('specialist', 'Specialist'), ('divergent', 'Divergent'), ('generalist', 'Generalist'), ('mystic', 'Mystic')], max_length=20)),
                ('purpose_seed', models.CharField(blank=True, max_length=200)),
                ('quiz_run_id', models.CharField(blank=True, max_length=100)),
                ('quiz_version', models.CharField(default='1.0', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_quiz_output', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Archetype Profile',
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=0)),
                ('heroic_path', models.CharField(blank=True, choices=[('earthwatcher', 'Earthwatcher'), ('peacebringer', 'Peacebringer'), ('storyteller', 'Storyteller'), ('innovator', 'Innovator'), ('dreamwalker', 'Dreamwalker'), ('truthseeker', 'Truthseeker')], max_length=20)),
                ('learning_path', models.CharField(blank=True, choices=[('scholar', 'Scholar'), ('wayfinder', 'Wayfinder'), ('specialist', 'Specialist'), ('divergent', 'Divergent'), ('generalist', 'Generalist'), ('mystic', 'Mystic')], max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('north_star_goal', models.TextField(blank=True)),
                ('powers', models.JSONField(default=list)),
                ('hours_of_impact', models.PositiveIntegerField(default=0)),
                ('impact_sources', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
    ]
