# Generated by Django 5.1.15 on 2026-08-13 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avatar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archetype', to='avatar.avatar'),
        ),
    ]
