# Generated by Django 5.1.15 on 2026-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetypeprofile',
            name='breakdowns',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='jupiter_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='mars_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='mercury_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='midheaven_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='neptune_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='pluto_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='saturn_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='uranus_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='archetypeprofile',
            name='venus_sign',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='archetypeprofile',
            name='purpose_seed',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
