# Generated by Django 5.1.15 on 2026-08-13 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avatar', '0001_initial'),
        ('starmap', '0002_constellation_angle_deg_constellation_is_north_star_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positive_balance', models.PositiveIntegerField(default=0)),
                ('negative_balance', models.PositiveIntegerField(default=0)),
                ('total_earned_lifetime', models.PositiveIntegerField(default=0)),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='avatar.avatar')),
            ],
            options={
                'verbose_name': 'LUX Wallet',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('issuance', 'LUX earned from validated milestone'), ('level_up', 'LUX consumed for level-up'), ('transfer', 'LUX+ sent to another avatar (v2)'), ('donation', 'LUX donated to mission/project (v2)'), ('spend', 'Cosmetic store purchase (v2+)')], max_length=20)),
                ('charge', models.CharField(choices=[('POS', 'Positive (LUX+)'), ('NEG', 'Negative (LUX-)'), ('CON', 'Consumed (level-up, non-cashable)')], max_length=3)),
                ('amount', models.PositiveIntegerField()),
                ('hero_action_type', models.CharField(blank=True, max_length=50)),
                ('lvm_scores', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('source_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lux_issuance', to='starmap.milestone')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lux.wallet')),
            ],
            options={
                'verbose_name': 'LUX Transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
